### ISSUE TITLE
科学哲学史の勉強

### ISSUE THREAD

**Issue by hibara428** [hibara428/zenn-content#7]
科学哲学史の勉強

---

- [ ] 科学哲学への招待 (野家啓一)
- [ ] 表現と介入 (イアン・ハッキング)
- [ ] 偶然を飼いならす (イアン・ハッキング)
- [ ] 数学はなぜ哲学の問題になるのか (イアン・ハッキング)
